sudo: required
services:
  - docker

before_install:
  - docker build -t emircm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emircm/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-048894545028"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY